// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeFidelidad.DbContext;

#nullable disable

namespace SistemaDeFidelidad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250101203049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeFidelidad.Models.ClienteParticipante", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCliente");

                    b.ToTable("ClientesParticipantes");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.DescuentosCliente", b =>
                {
                    b.Property<int>("IdDescuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDescuento"));

                    b.Property<int>("CantidadDescuento")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("IdTarjeta")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("IdDescuento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTarjeta");

                    b.ToTable("DescuentosClientes");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.Property<Guid>("IdTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("char(36)");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("IdTarjeta");

                    b.HasIndex("IdCliente");

                    b.ToTable("TarjetasFidelidad");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.DescuentosCliente", b =>
                {
                    b.HasOne("SistemaDeFidelidad.Models.ClienteParticipante", "Cliente")
                        .WithMany("Descuentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeFidelidad.Models.TarjetaFidelidad", "Tarjeta")
                        .WithMany("Descuentos")
                        .HasForeignKey("IdTarjeta");

                    b.Navigation("Cliente");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.HasOne("SistemaDeFidelidad.Models.ClienteParticipante", "Cliente")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.ClienteParticipante", b =>
                {
                    b.Navigation("Descuentos");

                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.Navigation("Descuentos");
                });
#pragma warning restore 612, 618
        }
    }
}
