// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeFidelidad.DbContext;

#nullable disable

namespace SistemaDeFidelidad.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeFidelidad.Models.ClienteParticipante", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CedulaCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCliente");

                    b.ToTable("ClientesParticipantes");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.DescuentosCliente", b =>
                {
                    b.Property<int>("IdDescuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDescuento"));

                    b.Property<int>("CantidadDescuento")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdTarjeta")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Usado")
                        .HasColumnType("bit");

                    b.HasKey("IdDescuento");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTarjeta");

                    b.ToTable("DescuentosClientes");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.Property<Guid>("IdTarjeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Puntos")
                        .HasColumnType("int");

                    b.HasKey("IdTarjeta");

                    b.HasIndex("IdCliente");

                    b.ToTable("TarjetasFidelidad");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.DescuentosCliente", b =>
                {
                    b.HasOne("SistemaDeFidelidad.Models.ClienteParticipante", "Cliente")
                        .WithMany("Descuentos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeFidelidad.Models.TarjetaFidelidad", "Tarjeta")
                        .WithMany("Descuentos")
                        .HasForeignKey("IdTarjeta");

                    b.Navigation("Cliente");

                    b.Navigation("Tarjeta");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.HasOne("SistemaDeFidelidad.Models.ClienteParticipante", "Cliente")
                        .WithMany("Tarjetas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.ClienteParticipante", b =>
                {
                    b.Navigation("Descuentos");

                    b.Navigation("Tarjetas");
                });

            modelBuilder.Entity("SistemaDeFidelidad.Models.TarjetaFidelidad", b =>
                {
                    b.Navigation("Descuentos");
                });
#pragma warning restore 612, 618
        }
    }
}
